const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

function readSource(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', relativePath), 'utf8')
}

test('quant decision pages share a consistent hero structure and one clear primary action', () => {
  const dashboardSource = readSource('src/views/quant/dashboard/index.vue')
  const jobsSource = readSource('src/views/quant/jobs/index.vue')
  const manualSource = readSource('src/views/quant/dispatch-manual/index.vue')
  const manualSummarySource = readSource('src/views/quant/dispatch-shared/ManualDispatchSummaryCard.vue')
  const autoSource = readSource('src/views/quant/dispatch-auto/index.vue')
  const detailSource = readSource('src/views/quant/dispatch-detail/index.vue')
  const executionSource = readSource('src/views/quant/execution/index.vue')
  const reviewSource = readSource('src/views/quant/review/index.vue')

  assert.equal(dashboardSource.includes('dashboard-hero__eyebrow'), true)
  assert.equal(dashboardSource.includes('查看今日主动作'), true)
  assert.equal(dashboardSource.includes('下一步去哪里'), true)
  assert.equal(dashboardSource.includes('dashboard-secondary-collapse'), true)

  assert.equal(jobsSource.includes('hero-eyebrow'), false)
  assert.equal(jobsSource.includes('hero-decision-card'), false)
  assert.equal(jobsSource.includes('dispatch-center-header'), true)
  assert.equal(jobsSource.includes('dispatch-center-status-line'), true)
  assert.equal(jobsSource.includes('jobs-secondary-collapse'), true)
  assert.equal(detailSource.includes('detail-secondary-collapse'), true)

  assert.equal(jobsSource.includes('返回调度中心'), false)
  assert.equal(manualSource.includes('hero-shell'), false)
  assert.equal(manualSource.includes('hero-decision-card'), false)
  assert.equal(manualSource.includes('manual-dispatch-header'), true)
  assert.equal(manualSource.includes('manual-dispatch-topline'), true)
  assert.equal(manualSummarySource.includes('执行任务'), true)
  assert.equal(manualSource.includes('查看本次提交摘要'), false)
  assert.equal(manualSource.includes('返回调度中心'), true)

  assert.equal(autoSource.includes('hero-shell'), false)
  assert.equal(autoSource.includes('hero-decision-card'), false)
  assert.equal(autoSource.includes('dispatch-auto-header'), true)
  assert.equal(autoSource.includes('dispatch-auto-topline'), true)
  assert.equal(autoSource.includes('dispatch-auto-secondary-collapse'), true)
  assert.equal(autoSource.includes('查看最近自动结果'), true)
  assert.equal(autoSource.includes('返回调度中心'), true)
  assert.equal(autoSource.includes('调度中心 / 自动触发视图'), true)
  assert.equal(autoSource.includes('发起手工调度'), false)

  assert.equal(detailSource.includes('刷新</el-button>'), true)
  assert.equal(detailSource.includes('返回调度中心'), true)
  assert.equal(detailSource.includes('开启自动刷新'), true)
  assert.equal(detailSource.includes('关闭自动刷新'), true)
  assert.equal(detailSource.includes('结果与异常'), true)

  assert.equal(executionSource.includes('execution-hero__title'), false)
  assert.equal(executionSource.includes('execution-page-header'), true)
  assert.equal(executionSource.includes('execution-topline'), true)
  assert.equal(executionSource.includes('execution-first-screen-grid'), true)
  assert.equal(executionSource.includes('secondary-section-collapse'), true)
  assert.equal(reviewSource.includes('review-conclusion-grid'), true)
  assert.equal(reviewSource.includes('review-secondary-collapse'), true)
})
